# Generated by Django 3.2.9 on 2021-11-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(default='', max_length=120, verbose_name='Фамилия'),
        ),
    ]
