# Generated by Django 3.2.9 on 2021-11-27 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driving_experience', models.PositiveIntegerField(verbose_name='Стаж вождения')),
                ('driver_license', models.CharField(max_length=120, verbose_name='Водительское удостоверение')),
                ('carrier_license', models.CharField(max_length=120, verbose_name='Лицензия перевозчика')),
                ('status', models.CharField(blank=True, choices=[('OTHER', 'Other'), ('IP', 'Ip'), ('LEGAL', 'Legal')], default='OTHER', max_length=20, verbose_name='Тип водителя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст жалобы')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='driver.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=120, verbose_name='Марка машины')),
                ('number', models.CharField(max_length=120, verbose_name='Госномер')),
                ('places', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('kids', models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество детских мест')),
                ('osago_number', models.CharField(max_length=30, verbose_name='Серия и номер')),
                ('osago_start', models.DateField(max_length=30, verbose_name='Дата регистрации')),
                ('osago_finish', models.DateField(max_length=30, verbose_name='Дата окончания')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='car', to='driver.driver')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
