# Generated by Django 3.2.9 on 2021-11-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_verify',
            field=models.BooleanField(default=True, verbose_name='Подтвержден'),
        ),
    ]
