# Generated by Django 3.2.9 on 2021-11-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20211127_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, max_length=120, verbose_name='Марка машины'),
        ),
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(blank=True, max_length=120, verbose_name='Госномер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='osago_finish',
            field=models.DateField(blank=True, max_length=30, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='car',
            name='osago_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Серия и номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='osago_start',
            field=models.DateField(blank=True, max_length=30, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='car',
            name='places',
            field=models.PositiveIntegerField(blank=True, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='carrier_license',
            field=models.CharField(blank=True, max_length=120, verbose_name='Лицензия перевозчика'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_license',
            field=models.CharField(blank=True, max_length=120, verbose_name='Водительское удостоверение'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driving_experience',
            field=models.PositiveIntegerField(blank=True, verbose_name='Стаж вождения'),
        ),
    ]
