# Generated by Django 3.2.9 on 2021-11-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerequest',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Общая стоимость заказа'),
        ),
    ]
