# Generated by Django 3.2.9 on 2021-11-27 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_routerequest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время позедки'),
        ),
        migrations.AddField(
            model_name='route',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.AddField(
            model_name='routerequest',
            name='check_in_location',
            field=models.CharField(blank=True, default=None, max_length=120, verbose_name='Место заезда'),
        ),
        migrations.AlterField(
            model_name='route',
            name='cargo_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена за кубический метр груза'),
        ),
        migrations.AlterField(
            model_name='route',
            name='passenger_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена за пассажира'),
        ),
        migrations.AlterField(
            model_name='routerequest',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('ACCEPTED', 'Accepted'), ('WAITING', 'Waiting'), ('CANCELED', 'Canceled')], max_length=20, verbose_name='Статус заявки'),
        ),
    ]
