# Generated by Django 3.2.9 on 2021-11-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_auto_20211127_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerequest',
            name='check_in_location',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Место заезда'),
        ),
    ]
